- name: Add In-Memory Inventory with Openstack Instances 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        ansible_user: cloud-user
        ansible_ssh_private_key_file: "~/.ssh/openstack.pem"
        group:
          - "{{ item.metadata.group }}"
          - "{{ item.metadata. deployment_name }}"
      loop: "{{ r_os_servers.openstack_servers }}"


- import_playbook: provision_database_tier.yml
- import_playbook: provision_app_tier.yml
- import_playbook: provision_load_balancer_tier.yml
